name: Laravel CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.PEM_FILE }}" > ~/.ssh/private_key.pem
          chmod 700 ~/.ssh/private_key.pem
      
      - name: set .env
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          chmod 700 .env
      
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Run tests
        run: vendor/bin/phpunit 

      - name: add known host
        run: |
          ssh-keyscan 143.110.242.52 >> ~/.ssh/known_hosts

      - name: deploy to server
        run: |
         ssh -i ~/.ssh/private_key.pem root@143.110.242.52 "cd /var/www/html/lara-ci-cd_2 && git pull origin master && composer install --no-interaction && chmod -R 777 storage bootstrap public"