name: Laravel CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.PEM_FILE }}" > ~/.ssh/private_key.pem
          echo "Secret value: ${{ secrets.PEM_FILE }} | sed 's/./& /g"
          chmod 700 ~/.ssh/private_key.pem
      
      - name: Show private key content
        run: cat ~/.ssh/private_key.pem
      
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Run tests
        run: vendor/bin/phpunit 

      - name: add known host
        run: |
          ssh-keyscan 143.110.242.52 >> ~/.ssh/known_hosts

      - name: deploy to server
        run: |
         ssh -i ~/.ssh/private_key.pem root@143.110.242.52 "cd /var/www/html/lara_ci_cd && git init --bare && git remote add production root@143.110.242.52:https://github.com/developerdesigner18/lara-ci-cd.git && git pull origin master && composer install --no-interaction"