name: Laravel CI/CD

on:
  push:
    branches:
      - master

env:
  PRIVATE_KEY_PATH: ${{ secrets.PRIVATE_KEY_PATH }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Run tests
        run: vendor/bin/phpunit

      - name: $PRIVATE_KEY_PATH
        run: |
          ssh -i /root/.ssh/dds.pem root@143.110.242.52 "cd /var/www/html/lara_ci_cd && git pull origin master && composer install --no-interaction && php artisan migrate"
